create extension if not exists pgcrypto;

create table if not exists public.vault_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  role text not null default 'viewer' check (role in ('admin','viewer')),
  active boolean not null default true,
  must_change_password boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vault_brands (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.vault_credentials (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.vault_brands(id) on delete cascade,
  platform text not null,
  login_url text,
  username text,
  recovery_email text,
  has_2fa boolean not null default false,
  notes text,
  secret_ciphertext text not null,
  secret_iv text not null,
  secret_tag text not null,
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vault_credentials_brand_id_idx on public.vault_credentials(brand_id);
create index if not exists vault_credentials_platform_idx on public.vault_credentials(platform);

create table if not exists public.vault_audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  credential_id uuid references public.vault_credentials(id) on delete set null,
  brand_id uuid references public.vault_brands(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.vault_profiles enable row level security;
alter table public.vault_brands enable row level security;
alter table public.vault_credentials enable row level security;
alter table public.vault_audit_logs enable row level security;

revoke all on public.vault_profiles from anon, authenticated;
revoke all on public.vault_brands from anon, authenticated;
revoke all on public.vault_credentials from anon, authenticated;
revoke all on public.vault_audit_logs from anon, authenticated;

create or replace function public.handle_vault_user_created()
returns trigger
set search_path = ''
language plpgsql
security definer
as $$
begin
  insert into public.vault_profiles (id, email, role, active)
  values (new.id, lower(new.email), 'viewer', true)
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke execute on function public.handle_vault_user_created() from public, anon, authenticated;

drop trigger if exists on_vault_auth_user_created on auth.users;
create trigger on_vault_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_vault_user_created();

insert into public.vault_brands(name)
values ('ALBI')
on conflict (name) do nothing;
